# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae3b218525c8b43341388f9fbc9bc2e52915bc33049cec814488207c134714bb1c03d81ee6c3db454b42f4923914424c01a25d42389a52e80a255300d6e75602

test:
  secret_key_base: 74ce12bcb0db863f0a735abe37f44eda95d1700ae4b5dfd9c16828bb4851dcf0a0dd7319a1242b8cf5b2d9c428d6fe9768a9ffcf307bbe4f8a9ef3c58a728240

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
